// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOadtqoJ-d6wpysM95h5kQsfBV1YistJY',
    appId: '1:929528357809:web:36fb352b69e22bc4229390',
    messagingSenderId: '929528357809',
    projectId: 'vegg0fresh-update',
    authDomain: 'vegg0fresh-update.firebaseapp.com',
    storageBucket: 'vegg0fresh-update.firebasestorage.app',
    measurementId: 'G-G3YX8RXG7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmML2VGc9i-dK3bwpB0wmpjVC7uRMJtDA',
    appId: '1:929528357809:android:d470081f518e8fc0229390',
    messagingSenderId: '929528357809',
    projectId: 'vegg0fresh-update',
    storageBucket: 'vegg0fresh-update.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaSSIhoLFuM409xJ3gJlKmSenHzTTGbxI',
    appId: '1:929528357809:ios:162f40ce4f877b84229390',
    messagingSenderId: '929528357809',
    projectId: 'vegg0fresh-update',
    storageBucket: 'vegg0fresh-update.firebasestorage.app',
    iosBundleId: 'com.veggofresh.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaSSIhoLFuM409xJ3gJlKmSenHzTTGbxI',
    appId: '1:929528357809:ios:b5507725a340ea81229390',
    messagingSenderId: '929528357809',
    projectId: 'vegg0fresh-update',
    storageBucket: 'vegg0fresh-update.firebasestorage.app',
    iosBundleId: 'com.example.vegonUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOadtqoJ-d6wpysM95h5kQsfBV1YistJY',
    appId: '1:929528357809:web:6890e8f89e540f04229390',
    messagingSenderId: '929528357809',
    projectId: 'vegg0fresh-update',
    authDomain: 'vegg0fresh-update.firebaseapp.com',
    storageBucket: 'vegg0fresh-update.firebasestorage.app',
    measurementId: 'G-X33P5KQK27',
  );
}
