// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbTvsDNFT2yKBszF-Po2C31TRgREjeUU',
    appId: '1:726384647343:web:f68f55f2beffba6b02885a',
    messagingSenderId: '726384647343',
    projectId: 'veggo-fresh-865c2',
    authDomain: 'veggo-fresh-865c2.firebaseapp.com',
    storageBucket: 'veggo-fresh-865c2.firebasestorage.app',
    measurementId: 'G-NZP9FMH95N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjiV7UDbVmmbJA6kLMMDEu2rMQNvhVug',
    appId: '1:726384647343:android:f7172ed40323c38f02885a',
    messagingSenderId: '726384647343',
    projectId: 'veggo-fresh-865c2',
    storageBucket: 'veggo-fresh-865c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4d23mjV1YaBzXmWF6-nYOiRfRGPBq5s',
    appId: '1:726384647343:ios:27a568f5e0587d0802885a',
    messagingSenderId: '726384647343',
    projectId: 'veggo-fresh-865c2',
    storageBucket: 'veggo-fresh-865c2.firebasestorage.app',
    iosBundleId: 'com.example.vegonUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP4d23mjV1YaBzXmWF6-nYOiRfRGPBq5s',
    appId: '1:726384647343:ios:27a568f5e0587d0802885a',
    messagingSenderId: '726384647343',
    projectId: 'veggo-fresh-865c2',
    storageBucket: 'veggo-fresh-865c2.firebasestorage.app',
    iosBundleId: 'com.example.vegonUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbTvsDNFT2yKBszF-Po2C31TRgREjeUU',
    appId: '1:726384647343:web:7ea0dbf2563368cc02885a',
    messagingSenderId: '726384647343',
    projectId: 'veggo-fresh-865c2',
    authDomain: 'veggo-fresh-865c2.firebaseapp.com',
    storageBucket: 'veggo-fresh-865c2.firebasestorage.app',
    measurementId: 'G-QVQPNBKPKB',
  );
}
